In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from datetime import datetime, timedelta
from datetime import date
import statistics as stat
from scipy import stats as scstats
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Create a numpy array called ‘height in inches’ from a list 10 of numbers:
# [66, 68, 71, 64, 61, 74, 64, 65, 70, 71].
height_in_inches = np.array([66, 68, 71, 64, 61, 74, 64, 65, 70, 71])
print(height_in_inches)

[66 68 71 64 61 74 64 65 70 71]


In [11]:
# Create a new array called ‘height_in_feet’ and make its values equal to the values in the first array divided by 12.
height_in_feet = (height_in_inches / 12)
print(height_in_feet)

[5.5        5.66666667 5.91666667 5.33333333 5.08333333 6.16666667
 5.33333333 5.41666667 5.83333333 5.91666667]


In [15]:
# Create a 5x5 array of zeros using np.zeros
array_of_zeros = np.zeros((5,5))
print(array_of_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
# Create an array of random floating point numbers between 0 and 100.
random_array = np.random.uniform(0,100, size = (5, 5))
print(random_array)

[[90.27220575 62.20371027 58.80192322 58.15532428 19.48030483]
 [49.87966576 77.70387269 24.19098442 47.79120689  8.65502528]
 [ 6.83846207  7.54370277 12.1368484  52.52921319 42.93322886]
 [27.77057614 46.88921306 87.55234018 60.33039518 39.12920963]
 [88.51240981  2.36141384 31.04314032 64.18929943 62.13684203]]


In [37]:
# Create an array of numbers from 0 to 75 in increments of 5.
zero_to_seventy_five = np.arange(0, 80, 5)
print(zero_to_seventy_five)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75]


In [43]:
# Part 2.
# Using the array below:
weather_data = np.array([
["2023-07-01", 30, 60, 0.1],
["2023-07-02", 31, 62, 0.2],
["2023-07-03", 29, 65, 0.0],
["2023-07-04", 33, 68, 0.5],
["2023-07-05", 34, 70, 0.3],
["2023-07-06", 32, 63, 0.1],
["2023-07-07", 30, 61, 0.0],
])
#  6. Provide the shape of the array
print(weather_data.shape)

(7, 4)


In [45]:
#  7. Return the last array in the array
print(weather_data[-1])

['2023-07-07' '30' '61' '0.0']


In [47]:
#  8. Find the day with the lowest temperature
lowest_temp_day = weather_data[np.argmin(weather_data[:, 1].astype(int)), 0]
print(lowest_temp_day)

2023-07-03
